### PR TITLE
:construction: feat(releasenotes) beta 010

### PR DESCRIPTION
**Pull request by Wabasi**

### CODE REVIEW

**Comment by Disturbing** [comment]
We could mention what is coming soon. But not a list of all the features we
don’t have? We can let Seb know separately if that’s what you are concerned
of

**Comment by bappr** [comment]
It's more for our customers to not ask all the time the same questions.
We had this dude asking for delete Kintoblock for example

**Comment by Wabasi** [comment]
So if we go ahead and do that. Should I just add a "Coming soon" Section towards the bottom of b 0.1.0 notes?

**Comment by bappr** [comment]
@Wabasi I think it would be cool yeah. @Disturbing what do u think?
(only for the features that were existing and do not exist anymore)

**Pull request merged**
